version: '3'
services:
  web:
    image: nginx
    links:
      - react
    ports:
      - "82:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/site.template:ro
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
  react:
    image: node:latest
    working_dir: /home/app
    links:
      - database
    depends_on:
      - database
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - "4000:4000"
    command: bash -c "yarn && yarn start"
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
       - ./database/mongo:/data/db
#  server:
#    image: node:latest
#    links:
#      - database
#    depends_on:
#      - database
#    working_dir: /home/app
#    volumes:
#      - ./server:/home/app/server
#      - ./interfaces:/home/app/interfaces
#      - ./graphql:/home/app/graphql
#      - ./package.json:/home/app/package.json
#      - ./next.config.js:/home/app/next.config.js
#      - ./tsconfig.json:/home/app/tsconfig.json
#      - ./.next:/home/app/.next
#      - /home/app/node_modules
#    command: bash -c "yarn && yarn build && yarn dev:server"